name: df-parallel-gpu
  
channels:
  - rapidsai
  - conda-forge

dependencies:
  - cudf=26.06.01
  - dask-cudf=26.06.01
  - pyspark=4.1.2 
  - openjdk=21.0.10
  - matplotlib
  - seaborn
  - papermill
  - jupyterlab
  - ipywidgets
  
variables:
  # SPARK conf directory with logging configuration
  SPARK_CONF_DIR: ../conf
  SPARK_DRIVER_MEMORY: 16G
  SPARK_DRIVER_MAXRESULTSIZE: 4G
  SPARK_WORKER_MEMORY: 4G
